name: Node.js Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sleep 5

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sleep 5

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5
  
  publish-gpr2:
    needs: 
      - publish-gpr
      - publish-npm
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5
